front: Support Safari
It does not support BigUint64Array yet, so use string instead.

https://caniuse.com/?search=BigUint64Array
https://bugs.webkit.org/show_bug.cgi?id=190800

Before this change, we get this error on Safari:
```
ReferenceError: Can't find variable: BigUint64Array
```